"""Render generated transport registries and the shared application composition."""

from __future__ import annotations

GENERATED_REGISTRY_HEADER = (
    "# Generated by arclith-cli; edit the binding modules instead."
)
GENERATED_COMPOSITION_HEADER = "# Generated by arclith-cli; do not edit manually."
LEGACY_REGISTRY_HEADER = (
    "# Generated by arclith-cli expose-usecase; edit the binding modules instead."
)
LEGACY_COMPOSITION_HEADER = (
    "# Generated by arclith-cli expose-usecase; do not edit manually."
)


def render_registry(entries: list[dict], via: str, composition_import: str) -> str:
    """Render deterministic registration for one installed transport."""
    transports = {
        "fastapi": ("from fastapi import APIRouter", "APIRouter"),
        "fastmcp": (
            "from typing import Any\nfrom fastmcp import FastMCP",
            "FastMCP[Any]",
        ),
        "langgraph": ("from langgraph.graph import StateGraph", "StateGraph"),
        "rabbitmq": (
            "from arclith.application.command_bus import CommandDispatcher",
            "CommandDispatcher",
        ),
    }
    imported, target = transports[via]
    lines = [
        GENERATED_REGISTRY_HEADER,
        "from __future__ import annotations",
        "",
        imported,
        f"from {composition_import} import (",
        "    ApplicationUseCases,",
        ")",
    ]
    lines.extend(_feature_router_imports(entries, via))
    lines.extend(_binding_imports(entries))
    lines += [
        "",
        "",
        "def register(",
        f"    target: {target},",
        "    use_cases: ApplicationUseCases | None = None,",
        "    *,",
    ]
    lines.extend(
        f"    {entry['usecase']}: {_pascal(entry['usecase'])}Port | None = None,"
        for entry in entries
    )
    lines += [
        ") -> None:",
        '    """Register the explicit public bindings on one transport target."""',
    ]
    lines.extend(_resolve_use_case_lines(entries))
    lines.extend(_registration_lines(entries, via))
    return "\n".join(lines) + "\n"


def _feature_router_imports(entries: list[dict], via: str) -> list[str]:
    if via != "fastapi":
        return []
    lines: list[str] = []
    for feature in _features(entries):
        lines.extend(
            (
                f"from {_feature_module(entries, feature)} import (",
                f"    build_router as build_{feature}_router,",
                ")",
            )
        )
    return lines


def _binding_imports(entries: list[dict]) -> list[str]:
    lines: list[str] = []
    for entry in entries:
        alias = _pascal(entry["usecase"])
        lines.extend(
            (
                f"from {entry['port_module']} import (",
                f"    {entry['port']} as {alias}Port,",
                ")",
                f"from {entry['binding_module']} import (",
                f"    register as register_{entry['usecase']},",
                ")",
            )
        )
    return lines


def _resolve_use_case_lines(entries: list[dict]) -> list[str]:
    lines: list[str] = []
    for entry in entries:
        lines += [
            f"    if {entry['usecase']} is None:",
            "        if use_cases is None:",
            f'            raise ValueError("Missing use case: {entry["usecase"]}")',
            f"        {entry['usecase']} = use_cases.{entry['usecase']}",
        ]
    return lines


def _registration_lines(entries: list[dict], via: str) -> list[str]:
    if via != "fastapi":
        return [
            f"    register_{entry['usecase']}(target, {entry['usecase']})"
            for entry in entries
        ]
    lines: list[str] = []
    for feature in _features(entries):
        lines.append(f"    {feature}_router = build_{feature}_router()")
        lines.extend(
            f"    register_{entry['usecase']}({feature}_router, {entry['usecase']})"
            for entry in entries
            if entry["options"]["feature"] == feature
        )
        lines.append(f"    target.include_router({feature}_router)")
    return lines


def _features(entries: list[dict]) -> tuple[str, ...]:
    return tuple(sorted({entry["options"]["feature"] for entry in entries}))


def _feature_module(entries: list[dict], feature: str) -> str:
    entry = next(item for item in entries if item["options"]["feature"] == feature)
    binding_module = entry["binding_module"]
    marker = f".routers.v1.{feature}."
    if marker not in binding_module:
        raise ValueError("FastAPI binding module does not match its feature")
    return binding_module.split(marker, 1)[0] + marker + "router"


def render_composition(entries: list[dict]) -> str:
    """Render one process composition shared by every installed transport."""
    repositories = _repository_bindings(entries)
    containers = _container_bindings(entries)
    lines = [
        GENERATED_COMPOSITION_HEADER,
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "",
        "from arclith import Arclith",
        *_composition_imports(entries, repositories, containers),
        "",
        "",
        "@dataclass(frozen=True)",
        "class ApplicationUseCases:",
        '    """One typed dependency graph shared by installed transports."""',
        "",
    ]
    lines.extend(
        f"    {entry['usecase']}: {_pascal(entry['usecase'])}Port" for entry in entries
    )
    lines += [
        "",
        "",
        "def build_use_cases(arclith: Arclith) -> ApplicationUseCases:",
        '    """Build concrete use cases at the process composition root."""',
        *_composition_body(entries, repositories, containers),
    ]
    return "\n".join(lines) + "\n"


def _composition_imports(
    entries: list[dict],
    repositories: dict[tuple[str, str], tuple[str, str]],
    containers: dict[tuple[str, str], tuple[str, str]],
) -> list[str]:
    lines: list[str] = []
    for entry in entries:
        alias = _pascal(entry["usecase"])
        factory = entry["factory"]
        lines.extend(
            (
                f"from {entry['port_module']} import (",
                f"    {entry['port']} as {alias}Port,",
                ")",
            )
        )
        if factory.get("container") is None and factory["module"] is not None:
            lines.extend(
                (
                    f"from {factory['module']} import (",
                    f"    {factory['class']} as {alias}UseCase,",
                    ")",
                )
            )
    for (module, builder), (builder_alias, _) in containers.items():
        lines.extend(
            (
                f"from {module} import (",
                f"    {builder} as {builder_alias},",
                ")",
            )
        )
    for (module, entity), (entity_alias, _) in repositories.items():
        lines.extend(
            (
                f"from {module} import (",
                f"    {entity} as {entity_alias},",
                ")",
            )
        )
    return lines


def _composition_body(
    entries: list[dict],
    repositories: dict[tuple[str, str], tuple[str, str]],
    containers: dict[tuple[str, str], tuple[str, str]],
) -> list[str]:
    missing = [
        entry["usecase"]
        for entry in entries
        if entry["factory"]["module"] is None
        and entry["factory"].get("container") is None
    ]
    if missing:
        names = ", ".join(missing)
        return [
            f'    raise RuntimeError("Implement application use cases before runtime composition: {names}")'
        ]
    lines = [
        f"    {repository_name} = arclith.repository({entity_alias})"
        for entity_alias, repository_name in repositories.values()
    ]
    lines.extend(
        f"    {container_name} = {builder_alias}(arclith)"
        for builder_alias, container_name in containers.values()
    )
    lines.append("    return ApplicationUseCases(")
    lines.extend(
        f"        {entry['usecase']}={_constructor(entry, repositories, containers)},"
        for entry in entries
    )
    lines.append("    )")
    return lines


def _constructor(
    entry: dict,
    repositories: dict[tuple[str, str], tuple[str, str]],
    containers: dict[tuple[str, str], tuple[str, str]],
) -> str:
    factory = entry["factory"]
    container = factory.get("container")
    if container is not None:
        key = (container["module"], container["builder"])
        return f"{containers[key][1]}.{container['attribute']}"
    alias = _pascal(entry["usecase"])
    if factory["repository_entity"] is None:
        return f"{alias}UseCase()"
    key = (factory["repository_entity_module"], factory["repository_entity"])
    return f"{alias}UseCase({repositories[key][1]})"


def _pascal(value: str) -> str:
    return "".join(part.title() for part in value.split("_"))


def _repository_bindings(
    entries: list[dict],
) -> dict[tuple[str, str], tuple[str, str]]:
    bindings: dict[tuple[str, str], tuple[str, str]] = {}
    for entry in entries:
        factory = entry["factory"]
        entity = factory["repository_entity"]
        module = factory["repository_entity_module"]
        if entity is None or module is None:
            continue
        key = (module, entity)
        bindings.setdefault(
            key,
            (
                f"{_pascal(entry['usecase'])}Entity",
                f"{entry['usecase']}_repository",
            ),
        )
    return bindings


def _container_bindings(
    entries: list[dict],
) -> dict[tuple[str, str], tuple[str, str]]:
    keys = sorted(
        {
            (container["module"], container["builder"])
            for entry in entries
            if (container := entry["factory"].get("container")) is not None
        }
    )
    return {
        key: (f"build_container_{index}", f"container_{index}")
        for index, key in enumerate(keys, start=1)
    }
