"""Plan and install deterministic, typed use case bindings without overwriting code."""

import json
from dataclasses import asdict, dataclass
from pathlib import Path

from arclith_cli.adapter_blueprints import BLUEPRINT_VERSION, render_feature_blueprint
from arclith_cli.binding_contract import UseCaseContract, inspect_usecase
from arclith_cli.binding_manifest import load_manifest
from arclith_cli.binding_options import resolve_binding_options
from arclith_cli.binding_rendering import (
    BindingOptions,
    native_module,
    render_binding,
    render_contract,
)
from arclith_cli.project_paths import ProjectPaths, detect_project_paths

TRANSPORTS = ("fastapi", "fastmcp", "langgraph", "rabbitmq")
_GENERATED_HEADER = (
    "# Generated by arclith-cli expose-usecase; edit the binding modules instead."
)
_GENERATED_COMPOSITION_HEADER = (
    "# Generated by arclith-cli expose-usecase; do not edit manually."
)


@dataclass(frozen=True)
class BindingPlan:
    files: dict[Path, str]
    preserved: tuple[Path, ...]
    options: BindingOptions
    project_dir: Path
    originals: dict[Path, bytes | None]


def plan_binding(
    project_dir: Path,
    usecase: str,
    *,
    via: str,
    feature: str | None = None,
    public_name: str | None = None,
    http_path: str | None = None,
    method: str | None = None,
    status_code: int = 200,
    command_type: str | None = None,
) -> BindingPlan:
    """Validate all choices and collisions before any filesystem mutation."""
    if via not in TRANSPORTS:
        raise ValueError(f"via must be one of {', '.join(TRANSPORTS)}")
    if not project_dir.is_dir():
        raise ValueError("Project directory does not exist")
    paths = detect_project_paths(project_dir)
    _check_containment(project_dir, (paths.inbound_ports,))
    contract = inspect_usecase(paths, usecase)
    options = resolve_binding_options(
        contract,
        via=via,
        feature=feature,
        public_name=public_name,
        http_path=http_path,
        method=method,
        status_code=status_code,
        command_type=command_type,
    )
    layer = "bidirectional" if via == "rabbitmq" else "inbound"
    root = paths.package_root / "adapters" / layer / via
    if not root.is_dir():
        raise ValueError(
            f"Install the {via} adapter with add-adapter before exposing its use cases"
        )
    prefix = paths.import_path("adapters", layer, via)
    manifest_path = project_dir / ".arclith/bindings" / f"{via}.json"
    _check_containment(project_dir, (root, manifest_path))
    entries = load_manifest(
        manifest_path, via, prefix, paths.import_path("domain", "ports", "inbound")
    )
    entry = {
        "usecase": contract.name,
        "port_module": contract.module,
        "port": contract.port,
        "binding_module": prefix
        + "."
        + native_module(contract, options).replace("/", "."),
        "options": asdict(options),
        "factory": {
            "module": contract.implementation_module,
            "class": contract.implementation,
            "repository_entity_module": contract.repository_entity_module,
            "repository_entity": contract.repository_entity,
        },
    }
    entries = _merge_entry(entries, entry, root, contract, options)
    planned, preserved = _developer_files(
        project_dir, root, contract, options, prefix, paths.package_name or ""
    )
    composition_entries = _composition_entries(paths, manifest_path, entries)
    planned.update(
        _generated_files(
            root,
            manifest_path,
            entries,
            via,
            paths.import_path("infrastructure", "use_cases_generated"),
            paths.package_root / "infrastructure" / "use_cases_generated.py",
            composition_entries,
        )
    )
    planned.update(_contract_test_files(project_dir, via, prefix, contract))
    planned = _changed_files(planned)
    _check_containment(project_dir, (*planned, *preserved))
    originals = {path: path.read_bytes() if path.exists() else None for path in planned}
    return BindingPlan(planned, preserved, options, project_dir, originals)


def _changed_files(planned: dict[Path, str]) -> dict[Path, str]:
    return {
        path: content
        for path, content in planned.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    }


def _merge_entry(
    entries: list[dict],
    entry: dict,
    root: Path,
    contract: UseCaseContract,
    options: BindingOptions,
) -> list[dict]:
    _check_collisions(entries, entry)
    registered = any(item["usecase"] == contract.name for item in entries)
    operation_files = (
        root / f"contracts/{contract.name}.py",
        root / (native_module(contract, options) + ".py"),
    )
    if not registered and any(path.exists() for path in operation_files):
        raise ValueError(
            "A developer file already occupies this binding; select a distinct use case name"
        )
    entries = sorted(
        [item for item in entries if item["usecase"] != contract.name] + [entry],
        key=lambda item: item["usecase"],
    )
    return entries


def _developer_files(
    project_dir: Path,
    root: Path,
    contract: UseCaseContract,
    options: BindingOptions,
    prefix: str,
    package: str,
) -> tuple[dict[Path, str], tuple[Path, ...]]:
    via = options.via
    rendered = (
        render_feature_blueprint(via, options.feature, package)
        if via in {"fastapi", "fastmcp"}
        else {}
    )
    rendered.update(
        {
            "contracts/__init__.py": '"""Transport contracts snapshotted from typed application requests."""\n',
            f"contracts/{contract.name}.py": render_contract(contract),
            native_module(contract, options) + ".py": render_binding(
                contract, options, prefix
            ),
        }
    )
    planned = {root / relative: content for relative, content in rendered.items()}
    _ensure_packages(project_dir, root, planned)
    preserved = tuple(sorted(path for path in planned if path.exists()))
    planned = {path: content for path, content in planned.items() if not path.exists()}
    return planned, preserved


def _generated_files(
    root: Path,
    manifest_path: Path,
    entries: list[dict],
    via: str,
    composition_import: str,
    composition_path: Path,
    composition_entries: list[dict],
) -> dict[Path, str]:
    planned: dict[Path, str] = {}
    registry = root / "bindings_generated.py"
    if registry.exists() and not registry.read_text(encoding="utf-8").startswith(
        _GENERATED_HEADER
    ):
        raise ValueError(f"Refusing to replace developer-owned registry {registry}")
    planned[registry] = _render_registry(entries, via, composition_import)
    if composition_path.exists() and not composition_path.read_text(
        encoding="utf-8"
    ).startswith(_GENERATED_COMPOSITION_HEADER):
        raise ValueError(
            f"Refusing to replace developer-owned composition {composition_path}"
        )
    planned[composition_path] = _render_composition(composition_entries)
    planned[manifest_path] = (
        json.dumps(
            {"version": BLUEPRINT_VERSION, "bindings": entries},
            indent=2,
            ensure_ascii=False,
        )
        + "\n"
    )
    return planned


def _composition_entries(
    paths: ProjectPaths,
    current_manifest: Path,
    current_entries: list[dict],
) -> list[dict]:
    by_usecase = {entry["usecase"]: entry for entry in current_entries}
    manifests = current_manifest.parent
    if not manifests.is_dir():
        return list(by_usecase.values())
    for path in sorted(manifests.glob("*.json")):
        if path == current_manifest or path.stem not in TRANSPORTS:
            continue
        layer = "bidirectional" if path.stem == "rabbitmq" else "inbound"
        prefix = paths.import_path("adapters", layer, path.stem)
        entries = load_manifest(
            path,
            path.stem,
            prefix,
            paths.import_path("domain", "ports", "inbound"),
        )
        for entry in entries:
            existing = by_usecase.get(entry["usecase"])
            if existing is not None and (
                existing["port_module"],
                existing["port"],
                existing["factory"],
            ) != (entry["port_module"], entry["port"], entry["factory"]):
                raise ValueError(
                    "A use case has inconsistent composition across transport manifests"
                )
            by_usecase.setdefault(entry["usecase"], entry)
    return [by_usecase[name] for name in sorted(by_usecase)]


def _contract_test_files(
    project_dir: Path, via: str, prefix: str, contract: UseCaseContract
) -> dict[Path, str]:
    planned: dict[Path, str] = {}
    test_path = (
        project_dir / "tests" / "adapters" / via / f"test_{contract.name}_contract.py"
    )
    if not test_path.exists():
        test_files = {
            test_path: _render_contract_test(
                prefix,
                contract.name,
                contract.module,
                contract.request,
                contract.transport_request,
            )
        }
        _ensure_packages(project_dir, project_dir / "tests", test_files)
        planned.update(test_files)
    return planned


def _render_contract_test(
    adapter_import: str, name: str, module: str, request: str, transport: str
) -> str:
    return (
        '"""Detect application input drift after the initial transport snapshot.\n\n'
        "When intentionally versioning a transport, replace this guard with examples\n"
        'covering the explicit migration mapper.\n"""\n\n'
        f"from {module} import (\n    {request},\n)\n"
        f"from {adapter_import}.contracts.{name} import (\n    {transport},\n)\n\n\n"
        f"def test_{name}_input_contract_has_not_drifted() -> None:\n"
        f"    application = {request}.model_json_schema()\n"
        f"    transport = {transport}.model_json_schema()\n"
        '    application.pop("title", None)\n'
        '    transport.pop("title", None)\n'
        "    assert transport == application\n"
    )


def apply_binding(plan: BindingPlan) -> tuple[Path, ...]:
    _check_containment(plan.project_dir, (*plan.files, *plan.preserved))
    for path, original in plan.originals.items():
        current = path.read_bytes() if path.is_file() else None
        if current != original or (path.exists() and not path.is_file()):
            raise ValueError(
                f"File changed after binding planning; rerun the command: {path}"
            )
    for path, content in plan.files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return tuple(plan.files)


def _check_collisions(entries: list[dict], entry: dict) -> None:
    for current in entries:
        if current["usecase"] == entry["usecase"]:
            if current != entry:
                raise ValueError(
                    "This use case already has a different binding; preserve and edit its public contract explicitly"
                )
            continue
        options = entry["options"]
        previous = current["options"]
        keys = (
            ("public_name", "command_type")
            if options["via"] == "rabbitmq"
            else ("public_name",)
        )
        if any(options[key] == previous[key] for key in keys):
            raise ValueError(
                "A binding already owns this public component name or command type"
            )
        if options["via"] == "fastapi" and (
            options["http_path"],
            options["method"],
        ) == (previous["http_path"], previous["method"]):
            raise ValueError("A binding already owns this HTTP method and path")


def _ensure_packages(project_dir: Path, root: Path, planned: dict[Path, str]) -> None:
    for path in list(planned):
        for parent in path.parents:
            if parent == root.parent or parent == project_dir:
                break
            init = parent / "__init__.py"
            if not init.exists():
                planned.setdefault(
                    init,
                    '"""Explicit adapter package; no import-time registrations."""\n',
                )


def _check_containment(project_dir: Path, paths: tuple[Path, ...]) -> None:
    resolved = project_dir.resolve()
    for path in paths:
        if not path.resolve().is_relative_to(resolved):
            raise ValueError(f"Binding path escapes the project: {path}")


def _render_registry(entries: list[dict], via: str, composition_import: str) -> str:
    transports = {
        "fastapi": ("from fastapi import APIRouter", "APIRouter"),
        "fastmcp": (
            "from typing import Any\nfrom fastmcp import FastMCP",
            "FastMCP[Any]",
        ),
        "langgraph": ("from langgraph.graph import StateGraph", "StateGraph"),
        "rabbitmq": (
            "from arclith.application.command_bus import CommandDispatcher",
            "CommandDispatcher",
        ),
    }
    imported, target = transports[via]
    lines = [
        _GENERATED_HEADER,
        "from __future__ import annotations",
        "",
        imported,
        f"from {composition_import} import (",
        "    ApplicationUseCases,",
        ")",
    ]
    if via == "fastapi":
        for feature in sorted({entry["options"]["feature"] for entry in entries}):
            lines.extend(
                (
                    f"from {entry_adapter_feature_module(entries, feature)} import (",
                    f"    build_router as build_{feature}_router,",
                    ")",
                )
            )
    for entry in entries:
        alias = _pascal(entry["usecase"])
        lines.extend(
            (
                f"from {entry['port_module']} import (",
                f"    {entry['port']} as {alias}Port,",
                ")",
                f"from {entry['binding_module']} import (",
                f"    register as register_{entry['usecase']},",
                ")",
            )
        )
    lines += [
        "",
        "",
        "def register(",
        f"    target: {target},",
        "    use_cases: ApplicationUseCases | None = None,",
        "    *,",
    ]
    lines.extend(
        f"    {entry['usecase']}: {_pascal(entry['usecase'])}Port | None = None,"
        for entry in entries
    )
    lines += [
        ") -> None:",
        '    """Register the explicit public bindings on one transport target."""',
    ]
    for entry in entries:
        lines += [
            f"    if {entry['usecase']} is None:",
            "        if use_cases is None:",
            f'            raise ValueError("Missing use case: {entry["usecase"]}")',
            f"        {entry['usecase']} = use_cases.{entry['usecase']}",
        ]
    if via == "fastapi":
        for feature in sorted({entry["options"]["feature"] for entry in entries}):
            lines.append(f"    {feature}_router = build_{feature}_router()")
            lines.extend(
                f"    register_{entry['usecase']}({feature}_router, {entry['usecase']})"
                for entry in entries
                if entry["options"]["feature"] == feature
            )
            lines.append(f"    target.include_router({feature}_router)")
    else:
        lines.extend(
            f"    register_{entry['usecase']}(target, {entry['usecase']})"
            for entry in entries
        )
    return "\n".join(lines) + "\n"


def entry_adapter_feature_module(entries: list[dict], feature: str) -> str:
    entry = next(item for item in entries if item["options"]["feature"] == feature)
    binding_module = entry["binding_module"]
    marker = f".routers.v1.{feature}."
    if marker not in binding_module:
        raise ValueError("FastAPI binding module does not match its feature")
    return binding_module.split(marker, 1)[0] + marker + "router"


def _render_composition(entries: list[dict]) -> str:
    repositories = _repository_bindings(entries)
    lines = [
        _GENERATED_COMPOSITION_HEADER,
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "",
        "from arclith import Arclith",
    ]
    for entry in entries:
        alias = _pascal(entry["usecase"])
        factory = entry["factory"]
        lines.extend(
            (
                f"from {entry['port_module']} import (",
                f"    {entry['port']} as {alias}Port,",
                ")",
            )
        )
        if factory["module"] is not None:
            lines.extend(
                (
                    f"from {factory['module']} import (",
                    f"    {factory['class']} as {alias}UseCase,",
                    ")",
                )
            )
    for (module, entity), (entity_alias, _) in repositories.items():
        lines.extend(
            (
                f"from {module} import (",
                f"    {entity} as {entity_alias},",
                ")",
            )
        )
    lines += [
        "",
        "",
        "@dataclass(frozen=True)",
        "class ApplicationUseCases:",
        '    """One typed dependency graph shared by installed transports."""',
        "",
    ]
    lines.extend(
        f"    {entry['usecase']}: {_pascal(entry['usecase'])}Port" for entry in entries
    )
    lines += [
        "",
        "",
        "def build_use_cases(arclith: Arclith) -> ApplicationUseCases:",
        '    """Build concrete use cases at the process composition root."""',
    ]
    missing = [
        entry["usecase"] for entry in entries if entry["factory"]["module"] is None
    ]
    if missing:
        names = ", ".join(missing)
        lines.append(
            f'    raise RuntimeError("Implement application use cases before runtime composition: {names}")'
        )
        return "\n".join(lines) + "\n"
    for entity_alias, repository_name in repositories.values():
        lines.append(f"    {repository_name} = arclith.repository({entity_alias})")
    lines.append("    return ApplicationUseCases(")
    for entry in entries:
        alias = _pascal(entry["usecase"])
        factory = entry["factory"]
        if factory["repository_entity"] is None:
            constructor = f"{alias}UseCase()"
        else:
            key = (
                factory["repository_entity_module"],
                factory["repository_entity"],
            )
            constructor = f"{alias}UseCase({repositories[key][1]})"
        lines.append(f"        {entry['usecase']}={constructor},")
    lines.append("    )")
    return "\n".join(lines) + "\n"


def _pascal(value: str) -> str:
    return "".join(part.title() for part in value.split("_"))


def _repository_bindings(
    entries: list[dict],
) -> dict[tuple[str, str], tuple[str, str]]:
    bindings: dict[tuple[str, str], tuple[str, str]] = {}
    for entry in entries:
        factory = entry["factory"]
        entity = factory["repository_entity"]
        module = factory["repository_entity_module"]
        if entity is None or module is None:
            continue
        key = (module, entity)
        bindings.setdefault(
            key,
            (
                f"{_pascal(entry['usecase'])}Entity",
                f"{entry['usecase']}_repository",
            ),
        )
    return bindings
