"""Plan and install deterministic, typed use case bindings without overwriting code."""

import json
import keyword
from dataclasses import asdict, dataclass
from pathlib import Path

from arclith_cli.adapter_blueprints import BLUEPRINT_VERSION, render_feature_blueprint
from arclith_cli.binding_contract import UseCaseContract, inspect_usecase
from arclith_cli.binding_options import resolve_binding_options
from arclith_cli.binding_rendering import (
    BindingOptions,
    native_module,
    render_binding,
    render_contract,
)
from arclith_cli.project_paths import detect_project_paths

TRANSPORTS = ("fastapi", "fastmcp", "langgraph", "rabbitmq")
_GENERATED_HEADER = (
    "# Generated by arclith-cli expose-usecase; edit the binding modules instead."
)


@dataclass(frozen=True)
class BindingPlan:
    files: dict[Path, str]
    preserved: tuple[Path, ...]
    options: BindingOptions
    project_dir: Path
    originals: dict[Path, bytes | None]


def plan_binding(
    project_dir: Path,
    usecase: str,
    *,
    via: str,
    feature: str | None = None,
    public_name: str | None = None,
    http_path: str | None = None,
    method: str | None = None,
    status_code: int = 200,
    command_type: str | None = None,
) -> BindingPlan:
    """Validate all choices and collisions before any filesystem mutation."""
    if via not in TRANSPORTS:
        raise ValueError(f"via must be one of {', '.join(TRANSPORTS)}")
    if not project_dir.is_dir():
        raise ValueError("Project directory does not exist")
    paths = detect_project_paths(project_dir)
    _check_containment(project_dir, (paths.inbound_ports,))
    contract = inspect_usecase(paths, usecase)
    options = resolve_binding_options(
        contract,
        via=via,
        feature=feature,
        public_name=public_name,
        http_path=http_path,
        method=method,
        status_code=status_code,
        command_type=command_type,
    )
    layer = "bidirectional" if via == "rabbitmq" else "inbound"
    root = paths.package_root / "adapters" / layer / via
    if not root.is_dir():
        raise ValueError(
            f"Install the {via} adapter with add-adapter before exposing its use cases"
        )
    prefix = paths.import_path("adapters", layer, via)
    manifest_path = project_dir / ".arclith/bindings" / f"{via}.json"
    _check_containment(project_dir, (root, manifest_path))
    entries = _load_manifest(
        manifest_path, via, prefix, paths.import_path("domain", "ports", "inbound")
    )
    entry = {
        "usecase": contract.name,
        "port_module": contract.module,
        "port": contract.port,
        "binding_module": prefix
        + "."
        + native_module(contract, options).replace("/", "."),
        "options": asdict(options),
    }
    entries = _merge_entry(entries, entry, root, contract, options)
    planned, preserved = _developer_files(
        project_dir, root, contract, options, prefix, paths.package_name or ""
    )
    planned.update(_generated_files(root, manifest_path, entries, via))
    planned.update(_contract_test_files(project_dir, via, prefix, contract))
    planned = _changed_files(planned)
    _check_containment(project_dir, (*planned, *preserved))
    originals = {path: path.read_bytes() if path.exists() else None for path in planned}
    return BindingPlan(planned, preserved, options, project_dir, originals)


def _changed_files(planned: dict[Path, str]) -> dict[Path, str]:
    return {
        path: content
        for path, content in planned.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    }


def _load_manifest(path: Path, via: str, prefix: str, port_prefix: str) -> list[dict]:
    manifest = (
        json.loads(path.read_text(encoding="utf-8"))
        if path.exists()
        else {"version": BLUEPRINT_VERSION, "bindings": []}
    )
    if (
        not isinstance(manifest, dict)
        or manifest.get("version") != BLUEPRINT_VERSION
        or not isinstance(manifest.get("bindings"), list)
    ):
        raise ValueError("Unsupported or invalid binding manifest")
    entries = manifest["bindings"]
    _validate_manifest_entries(entries, via, prefix, port_prefix)
    return entries


def _merge_entry(
    entries: list[dict],
    entry: dict,
    root: Path,
    contract: UseCaseContract,
    options: BindingOptions,
) -> list[dict]:
    _check_collisions(entries, entry)
    registered = any(item["usecase"] == contract.name for item in entries)
    operation_files = (
        root / f"contracts/{contract.name}.py",
        root / (native_module(contract, options) + ".py"),
    )
    if not registered and any(path.exists() for path in operation_files):
        raise ValueError(
            "A developer file already occupies this binding; select a distinct use case name"
        )
    entries = sorted(
        [item for item in entries if item["usecase"] != contract.name] + [entry],
        key=lambda item: item["usecase"],
    )
    return entries


def _developer_files(
    project_dir: Path,
    root: Path,
    contract: UseCaseContract,
    options: BindingOptions,
    prefix: str,
    package: str,
) -> tuple[dict[Path, str], tuple[Path, ...]]:
    via = options.via
    rendered = (
        render_feature_blueprint(via, options.feature, package)
        if via in {"fastapi", "fastmcp"}
        else {}
    )
    rendered.update(
        {
            "contracts/__init__.py": '"""Transport contracts snapshotted from typed application requests."""\n',
            f"contracts/{contract.name}.py": render_contract(contract),
            native_module(contract, options) + ".py": render_binding(
                contract, options, prefix
            ),
        }
    )
    planned = {root / relative: content for relative, content in rendered.items()}
    _ensure_packages(project_dir, root, planned)
    preserved = tuple(sorted(path for path in planned if path.exists()))
    planned = {path: content for path, content in planned.items() if not path.exists()}
    return planned, preserved


def _generated_files(
    root: Path, manifest_path: Path, entries: list[dict], via: str
) -> dict[Path, str]:
    planned: dict[Path, str] = {}
    registry = root / "bindings_generated.py"
    if registry.exists() and not registry.read_text(encoding="utf-8").startswith(
        _GENERATED_HEADER
    ):
        raise ValueError(f"Refusing to replace developer-owned registry {registry}")
    planned[registry] = _render_registry(entries, via)
    planned[manifest_path] = (
        json.dumps(
            {"version": BLUEPRINT_VERSION, "bindings": entries},
            indent=2,
            ensure_ascii=False,
        )
        + "\n"
    )
    return planned


def _contract_test_files(
    project_dir: Path, via: str, prefix: str, contract: UseCaseContract
) -> dict[Path, str]:
    planned: dict[Path, str] = {}
    test_path = (
        project_dir / "tests" / "adapters" / via / f"test_{contract.name}_contract.py"
    )
    if not test_path.exists():
        test_files = {
            test_path: _render_contract_test(
                prefix,
                contract.name,
                contract.module,
                contract.request,
                contract.transport_request,
            )
        }
        _ensure_packages(project_dir, project_dir / "tests", test_files)
        planned.update(test_files)
    return planned


def _render_contract_test(
    adapter_import: str, name: str, module: str, request: str, transport: str
) -> str:
    return (
        '"""Detect application input drift after the initial transport snapshot.\n\n'
        "When intentionally versioning a transport, replace this guard with examples\n"
        'covering the explicit migration mapper.\n"""\n'
        f"from {module} import {request}\n"
        f"from {adapter_import}.contracts.{name} import {transport}\n\n\n"
        f"def test_{name}_input_contract_has_not_drifted() -> None:\n"
        f"    application = {request}.model_json_schema()\n"
        f"    transport = {transport}.model_json_schema()\n"
        "    application.pop('title', None)\n"
        "    transport.pop('title', None)\n"
        "    assert transport == application\n"
    )


def apply_binding(plan: BindingPlan) -> tuple[Path, ...]:
    _check_containment(plan.project_dir, (*plan.files, *plan.preserved))
    for path, original in plan.originals.items():
        current = path.read_bytes() if path.is_file() else None
        if current != original or (path.exists() and not path.is_file()):
            raise ValueError(
                f"File changed after binding planning; rerun the command: {path}"
            )
    for path, content in plan.files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return tuple(plan.files)


def _check_collisions(entries: list[dict], entry: dict) -> None:
    for current in entries:
        if current["usecase"] == entry["usecase"]:
            if current != entry:
                raise ValueError(
                    "This use case already has a different binding; preserve and edit its public contract explicitly"
                )
            continue
        options = entry["options"]
        previous = current["options"]
        keys = (
            ("public_name", "command_type")
            if options["via"] == "rabbitmq"
            else ("public_name",)
        )
        if any(options[key] == previous[key] for key in keys):
            raise ValueError(
                "A binding already owns this public component name or command type"
            )
        if options["via"] == "fastapi" and (
            options["http_path"],
            options["method"],
        ) == (previous["http_path"], previous["method"]):
            raise ValueError("A binding already owns this HTTP method and path")


def _ensure_packages(project_dir: Path, root: Path, planned: dict[Path, str]) -> None:
    for path in list(planned):
        for parent in path.parents:
            if parent == root.parent or parent == project_dir:
                break
            init = parent / "__init__.py"
            if not init.exists():
                planned.setdefault(
                    init,
                    '"""Explicit adapter package; no import-time registrations."""\n',
                )


def _check_containment(project_dir: Path, paths: tuple[Path, ...]) -> None:
    resolved = project_dir.resolve()
    for path in paths:
        if not path.resolve().is_relative_to(resolved):
            raise ValueError(f"Binding path escapes the project: {path}")


def _validate_manifest_entries(
    entries: list[dict], via: str, adapter_import: str, port_import: str
) -> None:
    seen: set[str] = set()
    for entry in entries:
        _validate_manifest_entry(entry, via, adapter_import, port_import)
        if entry["usecase"] in seen:
            raise ValueError("Duplicate use case in binding manifest")
        seen.add(entry["usecase"])


def _validate_manifest_entry(
    entry: dict, via: str, adapter_import: str, port_import: str
) -> None:
    keys = {"usecase", "port_module", "port", "binding_module", "options"}
    if not isinstance(entry, dict) or set(entry) != keys:
        raise ValueError("Invalid binding manifest entry")
    _validate_manifest_options(entry["options"], via)
    for key in ("usecase", "port"):
        _validate_python_name(entry[key], module=False)
    for key in ("port_module", "binding_module"):
        _validate_python_name(entry[key], module=True)
    if not entry["binding_module"].startswith(adapter_import + "."):
        raise ValueError("Binding manifest module belongs to another adapter")
    if not entry["port_module"].startswith(port_import + "."):
        raise ValueError(
            "Binding manifest port belongs outside the application inbound ports"
        )


def _validate_manifest_options(options: dict, via: str) -> None:
    if not isinstance(options, dict) or set(options) != set(
        BindingOptions.__dataclass_fields__
    ):
        raise ValueError("Invalid binding manifest options")
    if options["via"] != via:
        raise ValueError("Invalid binding manifest transport")
    if any(
        not isinstance(value, str)
        for name, value in options.items()
        if name != "status_code"
    ):
        raise ValueError("Invalid manifest option value")


def _validate_python_name(value: str, *, module: bool) -> None:
    if not isinstance(value, str):
        raise ValueError("Invalid Python name in binding manifest")
    parts = value.split(".") if module else [value]
    if any(
        not part.isidentifier() or keyword.iskeyword(part) or part.startswith("_")
        for part in parts
    ):
        raise ValueError("Invalid Python name in binding manifest")


def _render_registry(entries: list[dict], via: str) -> str:
    transports = {
        "fastapi": ("from fastapi import FastAPI", "FastAPI"),
        "fastmcp": (
            "from typing import Any\nfrom fastmcp import FastMCP",
            "FastMCP[Any]",
        ),
        "langgraph": ("from langgraph.graph import StateGraph", "StateGraph"),
        "rabbitmq": (
            "from arclith.application.command_bus import CommandDispatcher",
            "CommandDispatcher",
        ),
    }
    imported, target = transports[via]
    lines = [_GENERATED_HEADER, "from __future__ import annotations", "", imported]
    for entry in entries:
        alias = (
            "".join(part.title() for part in entry["usecase"].split("_"))
            + "BindingPort"
        )
        lines += [
            f"from {entry['port_module']} import {entry['port']} as {alias}",
            f"from {entry['binding_module']} import register as register_{entry['usecase']}",
        ]
    lines += ["", "", f"def register(target: {target}, *,"]
    lines += [
        f"    {entry['usecase']}: {''.join(part.title() for part in entry['usecase'].split('_'))}BindingPort,"
        for entry in entries
    ]
    lines += [
        ") -> None:",
        '    """Supply constructed use cases once from infrastructure/bootstrap."""',
    ]
    lines += [
        f"    register_{entry['usecase']}(target, {entry['usecase']})"
        for entry in entries
    ]
    return "\n".join(lines) + "\n"
